Jekyll main configuration file

title: Tori Thompson
description: "Displaying previous assignments and projects in my path to learning c++, c#, javascript, html, css, php and sql"

permalink: date

timezone: America/Toronto

theme: minima 
look for themes on https://github.com/topics/jekyll-theme and https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme

Files to excludes from your website
exclude:  
- .gitignore
- CNAME 
